# fly.toml app configuration file generated for backend-services-qwp9aw on 2026-07-03T01:58:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-services-qwp9aw'
primary_region = 'ams'

[build]
  dockerfile = 'apps/api/Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3101'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 3101
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
